console.log("Hello! I'm your coding fun fact guide!");
let botName = "CodeBot";
let botLocation = "Silicon Valley";
let favoriteLanguage = "JavaScript";
console.log("My name is " + botName + " and I live on " + botLocation + ".");
console.log("My favorite programming language is " + favoriteLanguage + ".");
let codingFact = favoriteLanguage + " was created in just 10 days!";
console.log(codingFact);
codingFact = favoriteLanguage + " is primarily used for web development.";
console.log(codingFact);
codingFact = favoriteLanguage + " can run both on the client-side and the server-side!";
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - " + botName + " from " + botLocation + ".");